# Generated by Django 2.1.5 on 2020-03-28 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='inCharge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hall.Faculty'),
        ),
    ]
