# Generated by Django 2.2 on 2020-04-16 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0003_auto_20200416_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='id',
            field=models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='hall',
            name='inCharge',
            field=models.ForeignKey(default=1234, on_delete=django.db.models.deletion.PROTECT, to='hall.Faculty'),
        ),
    ]
