# Generated by Django 2.2 on 2020-04-16 14:51

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('hall', '0007_auto_20200416_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='inCharge',
            field=models.ForeignKey(default=1234, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Faculties',
                'ordering': ('first_name',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
