# Generated by Django 2.2 on 2020-04-20 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0009_auto_20200416_2057'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
