# Generated by Django 2.2.1 on 2020-04-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0011_auto_20200422_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='edate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='etime',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='sdate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='stime',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
