# Generated by Django 2.2.1 on 2020-04-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0014_auto_20200422_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
