# Generated by Django 2.2 on 2020-06-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0015_auto_20200423_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='edate',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='etime',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='sdate',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='stime',
        ),
        migrations.AddField(
            model_name='booking',
            name='eTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='sTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
