# Generated by Django 2.2.1 on 2020-07-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0016_auto_20200609_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default='Not Confirmed', max_length=50),
        ),
    ]
