# Generated by Django 2.2 on 2020-07-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0017_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sId', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('hod', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Staffs',
            },
        ),
    ]
