# Generated by Django 2.2 on 2020-07-06 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0018_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
