# Generated by Django 2.2 on 2020-07-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0019_delete_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('sId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('hod', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Staffs',
            },
        ),
    ]
